eureka:
  client:
    register-with-eureka: false
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Certificate-service-final
          uri: http://localhost:8082
          predicates:
            - Path=/certificates/**
        - id: Student-service-final
          uri: http://localhost:8081
          predicates:
            - Path=/studentdetails/**