spring:
  application:
    name: Certificate-service-final
  config:
    import: optional:configserver:http://localhost:8888


  datasource:
    url: jdbc:mysql://localhost:3306/certificate_final_data
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


