server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: ust-cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations